### ISSUE TITLE
Memory leaks in example code

### ISSUE THREAD

**Issue by pietercardoen** [pokowaka/jwt-cpp#18]
When executing the example code from Readme.md with link option -fsanitize=address, I get this error:

==10689==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 360 byte(s) in 3 object(s) allocated from:
    #0 0x7fdf490fe602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7fdf48c84e77 in CRYPTO_malloc (/lib/x86_64-linux-gnu/libcrypto.so.1.0.0+0x62e77)

SUMMARY: AddressSanitizer: 360 byte(s) leaked in 3 allocation(s).

**Comment by pietercardoen** [comment]
Thanks for fixing this :)
